### ISSUE TITLE
Rename Kind=SecretSink to Kind=PushSecret

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#1189]
As discussed in the community meeting today, the `Kind=SecretSink` should be renamed to `Kind=PushSecret` (or something else, we're open to suggestions - naming is really hard :sweat_smile: ). The current name really doesn't work when trying to speak it out loud, there's too much confusion between sink and sync etc :laughing:.

#976 

FYI @dominicmeddick @William-Young-97

**Comment by knelasevero** [comment]
ExternalSecret is a resource that tells the operator to grab a secret in an external provider and put in internally in your cluster.

What about InternalSecret? Following similar logic, it is an internal secret and we put it in an external provider?

This one will be hard to name.

Another weird idea: ExternalizedSecret, it's a secret that we artificially make external.

I still like PushSecret, it's very clear on what it proposes to do. But it is a bit different from what we have right now since it includes a verb in the name. 🤔

**Comment by moolen** [comment]
> ExternalizedSecret

There's too much character overlap with `ExternalSecret` and will cause confusion IMO. When imagining talking about the differences between the two it will be hard to understand.


I think it both Kind names don't necessarily need to make sense together - it would be great, for sure but this is more a nice-to-have attribute of the naming.
IMO when looking at the Kind name it should be completely unambiguous. It should be clear what it does, what kind of functionality it provides, what it represents or what kind of abstraction it provides.

Picking internal/external is kinda weird, because that very much depends on the point of view on how you look at the system: Internal in one context is actually external from a different point of view. Maybe it was a bad decision to call it `ExternalSecret` in the first place :smile:
I guess using PullSecret (instead of ExternalSecret) would make sense, but has too much overlap with ImagePullSecret and would cause confusion :shrug:. 

Anyways; following that definition above:
* `ExternalSecret` represents a credential that is stored in an external entity. It is pulled into Kubernetes and stored as a `Kind=Secret`. 
* `PushSecret` represents a credential that exists within the cluster as `Kind=Secret` and is pushed to an external entity

Not sure if this is the best answer/reasoning but
