### ISSUE TITLE
Removing/Renaming target Secret when renamed in ExternalSecret

### ISSUE THREAD

**Issue by zenyui** [external-secrets/external-secrets#1272]
**Describe the solution you'd like**
Hi 👋 - loving this project so far.

I noticed that if I create an `ExternalSecret` with an explicit `.spec.target.name` and then rename the target `Secret` in `.spec.target.name`, both the old and new `Secret` resources exist until I delete the `ExternalSecret` resource. I'd like an option to have "orphaned" target secrets removed when the `ExternalSecret` resource no longer references them. **NOTE:** when I delete the `ExternalSecret` resource, both `Secret` resources are deleted.

(Sorry if this is an option already, but I couldn't find it in the docs)

**What is the added value?**
- Orphaned k8s resources are a problem for many teams, as inevitably a developer will reference a resource that nobody is maintaining
- Since ExternalSecret resources can be configured as the `Owner` of the target secret, that should include cleaning up orphans (seems more intuitive)

**Give us examples of the outcome**
- user creates an `ExternalSecret` with `.spec.target.name: Foo` and `.spec.target.creationPolicy: 'Owner'`
- user updates `.spec.target.name` to `Bar`
- Secret `Bar` is created and secret `Foo` is deleted

**Observations (Constraints, Context, etc):**

- external-secrets helm chart v0.5.6
- GCP provider
- deployed on GKE

**Comment by zenyui** [comment]
@gusfcarvalho for my needs, I'm totally OK with that original secret just disappearing... :) 

Perhaps this is just an explicit, documented behavior of the `Owner` creationPolicy

**Comment by dacamposol** [comment]
@gusfcarvalho not ready, but I was thinking into something similar to the draft PR #1389

**Comment by gusfcarvalho** [comment]
Not stale!

**Comment by gusfcarvalho** [comment]
@dacamposol I've seen there's just some lint / unit testing errors that need to be covered there :)

**Comment by jolexa** [comment]
Greetings! I don't want to clutter up the implementation PR so I'll ask here. If https://github.com/external-secrets/external-secrets/pull/1389 is merged and released, will it clean up existing ES orphans once the version is deployed or shall I work to delete those manually for now?

**Comment by dacamposol** [comment]
> If https://github.com/external-secrets/external-secrets/pull/1389 is merged and released, will it clean up existing ES orphans once the version is deployed or shall I work to delete those manually for now?

@jolexa 

The implementation only deletes the secret upon deletion of the ES, but already existing orphans aren't taken into account...

While that logic could be included within the Operator, it would require to retrieve several secrets on each reconciliation cycle and it could put some strain in the Kubernetes API. Due to that, I'd delete them manually for the time being.

1. You could retrieve all the secrets within your cluster which are "owned" by an **ExternalSecret**:
```shell
SECRETS=$(kubectl get secrets -o yaml | yq '[.items.[] | .metadata | [{"name": .name, "namespace": .namespace, "owner": .ownerReferences.[] | select(.kind == "ExternalSecret")}] | .[]]')
echo -n $SECRETS | yq
```

2. Then, over those secrets, you can retrieve the ExternalSecret and compare the target name with your current name:
```shell
echo $SECRETS | yq '.[] | [{"namespace": .namespace, "name": .owner.name}]'
```

Probably, if you store the script of the second step in a variable, you could iterate over the index with `readarray` or similar and automate the check and deletion.
