### ISSUE TITLE
Enabling metrics collection with serviceMonitor enabled requires prometheus to be installed

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [external-secrets/external-secrets#1329]
**Describe the solution you'd like**
I did not realize that enabling metric collection also requires you to have already installed prometheus in your cluster.
For someone who uses open telemetry or datadog or splunk directly, you do not have prometheus installed, but those services can still scrape prometheus metrics
It would be good if the docs (https://external-secrets.io/v0.5.7/guides-metrics/) talked about this
It would also be nice if there was a way to enable scraping of metrics/exposing them to be collected without prometheus installed

**What is the added value?**
To collect metrics without prometheus

Right now you see this error if you try to set serviceMonitor.enabled = true, because the CRD Is not present in my cluster
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

**Comment by gusfcarvalho** [comment]
Hi @lorelei-rupp-imprivata ! I'm not familiar how other tools collect prometheus metrics. Do they use the old annotation approach from prometheus?

**Comment by lorelei-rupp-imprivata** [comment]
> Hi @lorelei-rupp-imprivata ! I'm not familiar how other tools collect prometheus metrics. Do they use the old annotation approach from prometheus?

Yeah usually the scrape annotations work, or if the metrics are exposed over a service. Basically these tools can parse/use prometheus scrape config, so as long as the metrics are exposed over a port and the /metrics path, they can collect them.

**Comment by lorelei-rupp-imprivata** [comment]
We also need a Service rolled out too so we can hit it to scrape the metrics like this https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/servicemonitor.yaml#L3
Essentially we need to support the Service without the ServiceMonitor

**Comment by cebidhem** [comment]
Hi @lorelei-rupp-imprivata,

I was looking for issues I could help with, found this one. Was about to propose a PR but actually, that is something you can already do by setting the following values to `true`:
`.Values.prometheus.enabled` --> https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/service.yaml#L1
`.Values.certController.prometheus.enabled` --> https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/cert-controller-service.yaml#L1
`.Values.webhook.prometheus.enabled` --> https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/webhook-service.yaml#L23

They say it's deprecated and will be removed in `0.7.0`, however if there's a use-case for non Prometheus scrappers (which I don't use at all), maybe instead of deprecating the entire service, they could deprecate only the scrape annotations and leave the service there.

If the project still wants to remove those services, I can propose a PR to have the possibility to only deploy the service in the serviceMonitor.yaml.

What do you think @gusfcarvalho ?

**Comment by gusfcarvalho** [comment]
First of all, thanks a lot @cebidhem for your help and will to contribute!!


I think what we can do is probably change the Prometheus value since now it is not referring to Prometheus anymore (maybe let the Prometheus one available until 0.7.0 with an “or” flag or by composing default values between Prometheus flag and the new one).

also adding this possibility to the metrics guide might be useful!

I think then we can remove the annotations on 0.7.0.

would you be interested in creating a PR for these changes @cebidhem? 😁

**Comment by lorelei-rupp-imprivata** [comment]
Thanks everyone this sounds great! Ill check out that deprecated flag too, i may have skipped over it because it was deprecated

**Comment by cebidhem** [comment]
This approach makes sense, I'll propose a PR in that direction soon!
