### ISSUE TITLE
Receive an error if enableVaultTokenCache is set and the last entry in LRU cache is not valid.

### ISSUE THREAD

**Issue by dops-at** [external-secrets/external-secrets#1790]
**Describe the solution you'd like**
Adding new vault tokens to the cache should not fail if the last token in LRU cache is not valid.

**What is the added value?**
You can use `enableVaultTokenCache` without problems.

**Give us examples of the outcome**

I'm using `enableVaultTokenCache` to be able create new RabbitMQ Users in vault rabbitmq engine. Without `enableVaultTokenCache` the generated user will be deleted immediately because of the [Close ](https://github.com/external-secrets/external-secrets/blob/5aaebf8bc0fe1f1eef3bbc4378445f5746d5de11/pkg/provider/vault/vault.go#L721-L731) method.

By using `enableVaultTokenCache` this code will not be executed and the generated token exists as long as the TTL of the token is valid. Yes, to get this thing working you need to make sure that the TTL of the RabbitMQ user is less than the TTL of the vault token.

But in some corner cases I get an error
`cannot setup new vault client: error while revoking token: Error making API request. URL: GET http://vault.active:8200/v1/auth/token/lookup-self Code: 403. Errors: * permission denied` 
when _ExternalSecret_ try's to read secrets from vault.

In my opinion it would be helpful to not fail if it is not possible to delete the token while a new one is created. Most likely in the [add ](https://github.com/external-secrets/external-secrets/blob/5aaebf8bc0fe1f1eef3bbc4378445f5746d5de11/pkg/provider/vault/cache.go#L84-L87) method. Just ignore the error (`revokeTokenIfValid(ctx, cachedClient.Client)`) and add the new cache.

**Comment by moolen** [comment]
I agree, it would be helpful to just log the error but proceed with the operation.
However, what are the corner cases to reproduce this issue? Looking at it, it seems the token expired while it was stored in cache. I would classify that as a bug. 

If the `revokeTokenIfValid()` fails that should trigger a reconciliation of the ES resource later on which then should succeed. Is that the case for you, is it "just" an intermittent error?

**Comment by moolen** [comment]
I see now, i went [through the docs](https://developer.hashicorp.com/vault/docs/secrets/rabbitmq). From what i understood, the `read` call returns a fresh set of rabbitmq credentials. They immediately expire because we `Close()` the client to revoke the token.

TBH, it was never intended to work with rabbitmq engine, but i'm glad you've tried it and i hope we find a way to make it work.


This should be solved with: https://github.com/external-secrets/external-secrets/pull/1640

This branch is quite old, can you give it a shot?

From the last [build job](https://github.com/external-secrets/external-secrets/actions/runs/3256836207/jobs/5347696846):
```
ghcr.io/external-secrets/external-secrets:v0.6.0-17.g2c54a4b6@sha256:0de0b5f7a81ef09c88d2289662b517ef39713d15f0acbd218880fc72653c9a8f
```

**Comment by dops-at** [comment]
I tried to use the image, and it is working but i was not able to reproduce the error from above.
