### ISSUE TITLE
Security of SecretStore provider credential secrets resources

### ISSUE THREAD

**Issue by jonatasbaldin** [external-secrets/external-secrets#19]
In our last community meeting we talked briefly about the security concerns on the `SecretStore` resources, since it has access keys to different Providers.

We talked about keeping `SecretStores` in the same namespace as the controller by default, or we can create a different namespace to manage it.

What do you think? What are the best practices around managing custom resources with sensitive information?

Cheers 👋

**Comment by mcavoyk** [comment]
In general, custom resources should not contain secret material, but instead a reference to the Kubernetes secret with the data.

SecretStore's should follow that and only contain references to the secret with the provider credentials, and the `controller` field on SecretStore's should increase the supportability of injected/native authentication by external-secret controllers such as [AWS IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) or [Vault Kubernetes authentication](https://www.vaultproject.io/docs/auth/kubernetes).

SecretStore's are namespaced and therefore should only be able to reference secrets within the same namespace. This should help prevent any unauthorized cross-namespace secret access as well.

**Comment by knelasevero** [comment]
SecretStores being namespaced and referecing a k8s secret in the same namespace is fine. I think that the concern here is more about SecretStore and the provider secrets that it references being in the target namespace together with the ExternalSecret and probably the app using the final target secret. People having access to this namespace, and having access to secrets in general, would now have access to provider credentials secret.

I think that we already can make sure that we leave the SecretStores and its provider credential secrets in another arbitrary namespace with what we have now, but maybe we should make it clear in the Readme or make our default deployment workflow guarantee that somehow?

**Comment by knelasevero** [comment]
I know that having access to secrets, or having credentials to access the same secrets in the external provider is not a super big problem, if this credentials only give access to the secrets, externally.

This becomes a big problem when this credentials give access to something more, by mistake. Like having access to other cloud provider resources with misconfigured  IAM on aws or google cloud.

**Comment by mcavoyk** [comment]
> This becomes a big problem when this credentials give access to something more, by mistake. Like having access to other cloud provider resources with misconfigured IAM on aws or google cloud.

External-secrets should have docs for the supported SecretStore providers with example permissions for the minimum access needed. This would allow users to better lock down the access of the credentials used by SecretStores.

> I think that the concern here is more about SecretStore and the provider secrets that it references being in the target namespace together with the ExternalSecret and probably the app using the final target secret. People having access to this namespace, and having access to secrets in general, would now have access to provider credentials **secret.**

I'm not sure the SecretStore resource is the best way to fix this, since the resource is namespaced and expected to reference provider secrets and be referenced within the same namespace.

ClusterSecretStore may provide a better method, since the provider secret used could be in an arbitrary namespace. Currently any namespace can create ExternalSecrets referencing a ClusterSecretStore, this does not really allow for secure multi-tenancy within a Kubernetes Cluster. A future enhancement could add the ability for ClusterSecretStore's to provide a condition clause where only those namespaces matching the condition can reference the store. Cluster administrators could create the ClusterSecretStore and then only entities in the allowlisted namespaces would be able to create ExternalSecrets referencing the store.

**Comment by knelasevero** [comment]
> External-secrets should have docs for the supported SecretStore providers with example permissions for the minimum access needed. This would allow users to better lock down the access of the credentials used by SecretStores.

I think that this already addresses the issue and is sufficient tbh :) When we add this to the documentation we can close this issue.

I think that you are right about SecretStore resource (and the secrets that it has access to) not being the best way to fix this. 

I like the allowlisted namespaces suggestion. Should we add this to the spec?

**Comment by knelasevero** [comment]
This is done, right (documented)? I am gonna glose this one, feel free to re-open if we still need to do something here.
