### ISSUE TITLE
Help understanding the purpose of the webhook/certcontroller components

### ISSUE THREAD

**Issue by grrttedwards** [external-secrets/external-secrets#1955]
Hello. I am trying to understand the purpose of the webhook deployment (and additionally the certcontroller).

Is there a high-level description of this component, and exactly which features it provides?

This issue https://github.com/external-secrets/external-secrets/issues/885 tried to explain it, but I'm still not sure I grasp this. I am a user of ESO, have Secrets Manager type secret stores, and haven't run myself into any problems (yet) with both certcontroller and webhook disabled.

I think there's room for that in the documentation, for example this page just says 

This page says https://external-secrets.io/v0.7.2/api/components/

> Exernal Secrets comes with three components: Core Controller, Webhook and Cert Controller.
>
> This is due to the need to implement conversion webhooks in order to convert custom resources between api versions and to provide a ValidatingWebhook for the ExternalSecret and SecretStore resources.
>
> These features are optional but highly recommended. You can disable them with helm chart values certController.create=false and webhook.create=false.

**Comment by moolen** [comment]
great question, i guess it's worth adding that explicitly to that section!

There are two needs: 
(1) conversion webhook
We have different versions `v1alpha1`, `v1beta1` and hopefully soon `v1`. The controller however is bound to one particular version. To support all versions you need a conversion webhook.

(2) validating webhook
We do validate ExternalSecret and SecretStore resources for validity. There are some things that you can't do with OpenAPI validation (which is baked into the CRD).


Because all webhooks served over TLS one must provide/manage TLS certificates and private keys for it - hence the certcontroller. It is need to generate/update the TLS certs AND it injects it into the `Kind=CustomResourceDefinition` and `Kind=ValidatingWebhookConfiguration` . You can run ESO without webhooks if you use only the `v1beta1` version (and you don't want the extended validation part).

**Comment by grrttedwards** [comment]
Thanks! So it does sound like I should enable both of them, given that I don't _intend_ to restrict API versions used, and that the additional validation sounds like it would be handy.

Are there any gotchas to enabling them once there are already ExternalSecrets, SecretStores, and the core controller running?

**Comment by moolen** [comment]
Theoretically `Kind=SecretStores` could be considered invalid by the webhook, but if they're fine now it's quite unlikely they get rejected.

The controllers modify `Kind=CustomResourceDefinition` and `Kind=ValidatingWebhookConfiguration`. You may need to adapt the way you install ESO and the CRDs.
