### ISSUE TITLE
Make keeper Secrets Manager work with complex types

### ISSUE THREAD

**Issue by ppodevlabs** [external-secrets/external-secrets#2049]
**Describe the solution you'd like**
Keeper security have different types of records as explained in the [Documentation](https://docs.keeper.io/secrets-manager/secrets-manager/about/field-record-types#default-record-types).

At the moment, the actual implementation do not support complex secret. Only secrets with string fields.

**What is the added value?**
It will allow users to work with most of the records types in keeper reducing errors and limitations.

**Comment by makeaweli** [comment]
According to the [Provider docs in this repo](https://external-secrets.io/latest/provider/keeper-security/#limitations):
> Keeper Secret Manager does not work with General Records types nor legacy non-typed records

What exactly is a `General Record`? I don't see any mention/definition in the [official Keeper docs](https://docs.keeper.io/secrets-manager/secrets-manager/about/field-record-types#encryptednotes-secure-note).

At present the only record type that I can fetch is [encryptedNotes](https://docs.keeper.io/secrets-manager/secrets-manager/about/field-record-types#encryptednotes-secure-note). I'm guessing because the returned type is strictly string.

**Comment by DT0002** [comment]
is anyone working on this ? We are also looking to use attachments from keeper security

**Comment by gusfcarvalho** [comment]
Hi @DT0002 ! I believe no one is working on this, as this is a community-driven provider. If you want to give it a try, I can reopen the issue and assign it to you, but just to level the expectations that community providers have features built in almost exclusively by the community :)

**Comment by DT0002** [comment]
check : https://github.com/external-secrets/external-secrets/pull/3016 keeper security support for complex types
