### ISSUE TITLE
Context deadline exceeded when calling ESO webhook due to network policies

### ISSUE THREAD

**Issue by mzylowski** [external-secrets/external-secrets#2200]
Hello,
I'm trying to use ESO in version 0.7.1 on GKE clusters where networking policies are managed by k8s network policies (in namespaces) and [tigera (calico) GlobalNetworkPolicies](https://docs.tigera.io/calico/latest/reference/resources/globalnetworkpolicy) for entire cluster.

When I tried to deploy ClusterSecretStore object (by helm chart deployed by helmfile tool) I see:
```
ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Internal error occurred: failed calling webhook "validate.clustersecretstore.external-secrets.io": failed to call webhook: Post "https://external-secrets-operator-eso-webhook.prod-vault.svc:443/validate-external-secrets-io-v1beta1-clustersecretstore?timeout=5s": context deadline exceeded

COMBINED OUTPUT:
  Release "eso-prerequisites" does not exist. Installing it now.
  Error: Internal error occurred: failed calling webhook "validate.clustersecretstore.external-secrets.io": failed to call webhook: Post "https://external-secrets-operator-eso-webhook.prod-vault.svc:443/validate-external-secrets-io-v1beta1-clustersecretstore?timeout=5s": context deadline exceeded
``` 

I'm lack of ideas how I should prepare traffic rules for my cluster to make it work.
Some questions:
* From where is this webhook called? From a namespace where ClusterSecretStore is created? Or kube-system or from operator so eso namespace? 
* Do I need only connectivity between ESO pods? Or do I also need some connectivity to kubelet or apiserver or ...?
* This `context deadline exceeded` error can appear only in case when this is a connectivity issue or also due to other reasons?

Thanks in advance for any help. :)

**Comment by moolen** [comment]
The control-plane needs to talk to eso webhook.

In order to use the webhook with a GKE cluster, you must configure an additional firewall rule to allow the GKE control plane access to your webhook pod.

You can read more information on how to add firewall rules for the GKE control plane nodes in the [GKE docs](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules).

([shamelessly copied from cert-manager docs](https://cert-manager.io/docs/installation/compatibility/#gke))

**Comment by mzylowski** [comment]
Closing this one - issue was on our side with rules configuration, but the suggestion about control-plane connectivity was useful. Thanks!
