### ISSUE TITLE
Annotation is not working with new external-secret-operator

### ISSUE THREAD

**Issue by sam-germany** [external-secrets/external-secrets#2236]
In old Kubernetes-external-secrets we can use annotations to filter the key as per NameSpace name and i have somehow modife it 

externalsecrets.kubernetes-client.io/permitted-key-name: (\/kes\/({{ $key }}/.*

like this that only keys that included the same NameSpace name can be fetched inside the namespace, this option was very usefull to seperate the secrets as per namespace, but this annotation is not working with the New external-secret-operator.

https://github.com/external-secrets/kubernetes-external-secrets

![4re](https://user-images.githubusercontent.com/66065583/232898804-c327708c-a5f6-444a-a000-2c9fe6ec3261.png)

**Comment by gusfcarvalho** [comment]
Hi @sam-germany. This is feature was intentionally not ported from KES. The reasoning is that this type of control was needed on KES, but not on ESO (as the KES project only ran on one service account; while on ESO, since you can leverage multiple service accounts with it, the permissions for secret accessing is better handled at your provider access control).

if you really wish that feature, you can achieve it with gatekeeper or kyverno as well.

**Comment by sam-germany** [comment]
Hi @gusfcarvalho It will be very much helpful if you can privide me some documentation link that how i achive this feature as you explain using multiple service accounts and with the permissions for secret acessing per NameSapce.

**Comment by gusfcarvalho** [comment]
You should see here: https://external-secrets.io/v0.8.1/introduction/overview/
