### ISSUE TITLE
Missing things in the docs that we noticed during kubecon

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#2242]
- [x] Better explain PushSecrets and maybe include a diagram
- [ ] Explain all generator types and how it works
- [ ] Explain sourceref (maybe deprecate secrestoreref)
- [ ] Have a guide for pushsecret
(feel free to add more and create sub-issues)

**Comment by sebagomez** [comment]
Hey all, [this](https://external-secrets.io/v0.8.1/api/pushsecret/) should be the place to document `PushSecret`, right? No wonder people asked to "better" explain it! :D

**Comment by moolen** [comment]
Yeah, under the `api/` we cover the concepts: context, structure and mechanics of a given resource.
Under `guides/` we can/should have a walkthrough/task approach on how to implement this with a given example.

I guess it would also make sense to structure the `Guides` Page so that the different articles are categorised into:

* ExternalSecret
* PushSecret
* Generator
* Operations/Misc/??? :shrug: 

We should also reword some titles where appropriate
