### ISSUE TITLE
Don't update ConfigMaps/Secrets if nothing has changed

### ISSUE THREAD

**Issue by phoenix-bjoern** [external-secrets/external-secrets#2495]
ESO updates ConfigMaps and Secrets according to the refreshInterval in the ExternalSecret. While it is desired to check for changed secrets by this interval, it may not desired to actually modify the ConfigMap/Secret in K8S if nothing has changed in the secret source/store or the ExternalSecret. In fact at least the resourceVersion gets incremented on each update interval by ESO (tested with v0.8.1).

There are several processes which trigger a reload of their configuration or even restart pods on updates of their depending resources. And if they are not "smart" to detect actual changes in the data the frequent updates of the K8S objects can "stress" them. For example nginx ingress detects changes in referenced secrets for BasicAuth credentials and triggers a reload of its configuration even if the credentials haven't changed.
To avoid this stressful situation for depending workloads - and K8S in general - ConfigMaps and Secrets shouldn't be updated/touched if nothing has changed. This will significantly reduce "update pressure" in all K8S components.

So instead of updating the objects and increment the resourceVersion, the "reconcile.external-secrets.io/data-hash" annotation should be reconciled (as the name indicates ;-) ) and only if it is different, perform the update of the object. This should significantly improve the stability of the cluster when dealing with hundreds or thousands of ExternalSecrets with low refreshInterval setting.

**Comment by phoenix-bjoern** [comment]
I read the code a bit and maybe this is issue isn't a feature request but a bug. In https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L343 the comparison of the existing object and the new one should skip the update:
```go
	if equality.Semantic.DeepEqual(existing, obj) {
		return nil
	}
``` 

So I think this comparison fails even if the actual data is equal.
Requires deeper investigation to understand why the objects are different or at least the method considers them as different.

**Comment by phoenix-bjoern** [comment]
Think I found the problem: We are using htpasswd in the secret template:
```
auth: '{{ htpasswd .basic_auth_username .basic_auth_password }}'
``` 

This generates always a new string which is different from the previous one. Therefore the comparison fails and the update of the secret is processed. Probably htpasswd should be avoided then.

Issue can be closed, maybe this helps someone else to identify issues.

**Comment by werwolfby** [comment]
@phoenix-bjoern thank you! My long time googling finally points to this issue, that helped me understand my exact problem.
I still this is bug in `external-secrets` and there should be a workaround for solve it. Because this is really nice that I can use supported `htpasswd` function in my templates.

**Comment by phoenix-bjoern** [comment]
@werwolfby actually I don't think it is possible to solve the problem in ESO. htpasswd returns a new string on every call. So the comparison of existing and newly generated secret will always trigger an update of the K8S secret. IMHO, although available in the string library, htpasswd should be omitted in ExternalSecrets - at least for frequent updates and/or in clusters with many secrets.

**Comment by werwolfby** [comment]
@phoenix-bjoern I agree with you. But if instead of compare secret data itself ESO could compare secrets and template string itself (by comparing hash for simplicity and for not storing secrets themself).
And this would solve the issue. As you did I didn't expect such behavior. As developer I understand why it happened and would implemented it in the same way on first implementation as most obvious solution. We didn't own this functions.

So as I proposed in my issue it could be solved. Or at least should be mentioned in docs, because removing it from supported funcs will be a breaking change. Thought it should be done initially, because it [already removes few funcs](https://github.com/external-secrets/external-secrets/blob/9559c2a124ede009a6d649b36ff3f3ed57cd9fb4/pkg/template/v2/template.go#L59-L61):

```golang
func init() {
	sprigFuncs := sprig.TxtFuncMap()
	delete(sprigFuncs, "env")
	delete(sprigFuncs, "expandenv")
```

**Comment by phoenix-bjoern** [comment]
@werwolfby True, but then ESO would have to save hashes of the secrets and templates and AFAIK this is not the case. ESO uses its' CR and the K8S Secrets as "storage". So hashes of the values would have to be stored as annotations but that requires additional business logic just for that specific case...

**Comment by gusfcarvalho** [comment]
@phoenix-bjoern to some degree this would be possible, but I think this would cause problems when reconciling. We're further discussing this specific issue in here https://github.com/external-secrets/external-secrets/issues/2699

**Comment by werwolfby** [comment]
@phoenix-bjoern hash already stored as annotation in target secrets: `reconcile.external-secrets.io/data-hash`. And it is used to find changes.
