### ISSUE TITLE
Alternative way to debug or build local changes faster

### ISSUE THREAD

**Issue by laisramos123** [external-secrets/external-secrets#2753]
**Describe the issue**
I was looking for a way to run/debug the project faster.

**Describe the solution you'd like**
Maybe a way to run the project without using helm, because it installs all Kubernets resources, which is not ideal for quick tests or for those just starting out in the project.

**Describe alternatives you've considered**
Me and my team are considered use a alternative for helm, like kind or k3s

**Comment by 812142** [comment]
Checked issue

**Comment by shuheiktgw** [comment]
Hi, @laisramos123 👋 
I appreciate your interest in contributing to the project!

> Maybe a way to run the project without using helm, because it installs all Kubernets resources, which is not ideal for quick tests or for those just starting out in the project.

Hmm, I personally believe using Helm is the best way for users to start off the project since it installs all the necessary components. Manually installing them is almost impossible for beginners since that requires relatively advanced knowledge of the controllers. 

 If you are interested in debugging the controllers locally, check out [our dev guide](https://external-secrets.io/main/contributing/devguide/), which explains how to run the controllers locally 🙂
