### ISSUE TITLE
CPU Leak when operator cant find Secret

### ISSUE THREAD

**Issue by Spazzy757** [external-secrets/external-secrets#288]
**Describe the solution you'd like**
When the secret operator cant find secrets it seems to exponentially increase the cpu usage overtime. Maybe a default retry amount times would be useful here as this could inadvertantly crash systems if left unchecked (noisy neighbours)

**What is the added value?**
More production ready. Less chance of misconfiguration causing the operator to kill a node with high cpu usage

**Observations (Constraints, Context, etc):**

Heres a 24 hour graph. for some context I deployed around 40 External secrets reading from GCSM, I have been migrating over from another solutions and it takes time to update GCSM with the secrets so there are around 20 secrets that the operator cant find (this is fine as I was working through this), but I started getting alerts of high cpu usage:

![image](https://user-images.githubusercontent.com/19777480/127107097-bdc13621-91e1-4c41-9119-4d501213ce4c.png)

The node with the cpu spike their is external secret operator. The point where it falls is where I deleted the pod.

**Comment by moolen** [comment]
Hey @Spazzy757 thanks for reporting, we'll take a look into it! 
Do you have more information like `sync_calls` metric or log events that might indicate what code paths were triggered excessively?

**Comment by moolen** [comment]
Just from reading the source code and having the information you provided i would guess that the problem lies here:


https://github.com/external-secrets/external-secrets/blob/59a851c941c37aad703c08565aefe9f09649c498/pkg/controllers/externalsecret/externalsecret_controller.go#L379-L382

When the provider errors, the `.Close()` doesn't get called. It must called as `defer providerClient.Close()`.
AFAIK only the GCP provider actually makes use of the `Close()` method.

**Comment by Spazzy757** [comment]
Thanks for the awesome quick fix @moolen

**Comment by neocycf** [comment]
Memory leak fixed. Thanks!
