### ISSUE TITLE
Enable Auth.JWTAuth.ServiceAccountRef.Namespace in kind SecretStore

### ISSUE THREAD

**Issue by dfallert-rcd** [external-secrets/external-secrets#366]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

I would like to deploy ESO as a service, like shown here
https://external-secrets.io/guides-multi-tenancy/#eso-as-a-service

In order to do so, I would need the `SecretStore` kind in `namespace: foo` to be ServiceAccount in the ESO's `namespace: bar`

currently this seems to not be possible because, as shown here https://github.com/external-secrets/external-secrets/blob/e65658d543a759b1d71f2774951f0d473d6201e2/apis/meta/v1/types.go#L36-L37 the namespace field is 
> Ignored if referent is not cluster-scoped.

so as `SecretStore` is namespaced, this field is ignored, and I believe this is proven by this if statement https://github.com/external-secrets/external-secrets/blob/8827e3ab92cdd87800f44d8f8bd995f0ea749476/pkg/provider/aws/auth/auth.go#L162-L164

which shows that the namespace is only set, if the kind is `ClusterSecretStoreKind`

and further proven by, when you try to use that field anyway like so
``` YAML
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
#~~~omitted
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      role: role-arn
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: kube-system
```

Any `ExternalSecret` that references the above `SecretStore`, gives this status
```
Status:
  Conditions:
    Last Transition Time:   2021-09-03T21:49:36Z
    Message:                unable to create session: ServiceAccount "external-secrets" not found
    Reason:                 SecretSyncedError
    Status:                 False
    Type:                   Ready
  Refresh Time:             2021-09-03T21:48:47Z
  Synced Resource Version:  2-2002c35b18294bb8b98d9388d1323a86
```

**Comment by moolen** [comment]
This is by design: A namespaced `SecretStore` should only be able to reference secrets, config-maps or service-accounts from the same namespace. If we give this up a user can easily escalate privileges by using SAs from other namespaces.

We have one proposal that allows a `ClusterSecretStore` to be scoped to a particular set of namespaces: https://github.com/external-secrets/external-secrets/issues/163#issuecomment-896049333

I'd suggest provisioning the service account into the correct namespace und use a SecretStore to reference it. If you share this service account across multiple i suggest using a ClusterSecretStore.

Would that work for your use-case?

**Comment by dfallert-rcd** [comment]
> This is by design: A namespaced SecretStore should only be able to reference secrets, config-maps or service-accounts from the same namespace. If we give this up a user can easily escalate privileges by using SAs from other namespaces.

then how would you propose using [ESO as a service](https://external-secrets.io/guides-multi-tenancy/#eso-as-a-service) with [AWS IRSA](https://external-secrets.io/provider-aws-secrets-manager/#eks-service-account-credentials)?

> Would that work for your use-case?

I don't believe so. However, it could be me misunderstanding something on my part.

We have ESO in its own namespace, with its own service account and IAM role to assume other IAM roles, then we have developers creating their own secret stores, using their own specific IAM roles for the ESO to assume when gathering their secrets from AWS. Where this breaks is the `serviceAccountRef` as referenced above, as the namespaced secret stores can't reference the ESO service account.

**Comment by jbilliau-rcd** [comment]
@moolen  we are trying to replicate what I consider to be a perfect scenario for enterprises with the original kubernetes-external-secrets controller from GoDaddy. With that controller:

1. We deploy it to kube-system, having it auth to AWS using IRSA via `ServiceAccount` annotations.
2. We then allow **token-file-web-identity** (which is what it ends up using in Kubernetes) to use our application-specific pod IAM role, which has access to the secrets. In this way, the controller itself has no access to anything, it only has access to assume the roles *which do*.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::999999999:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/XXXXXXXXXXX"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-east-2.amazonaws.com/id/XXXXXXXXXXXXXX:sub": "system:serviceaccount:test-whale:test-whale"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "AROAWCVBJZDDEKCNME2DM:token-file-web-identity"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

So the first block allows the application pod to assume the role, the second block allows the external-secrets controller to assume the role (to go get the secrets).

3. We then specify this on our `ExternalSecret`

```
spec:
    backendType: secretsManager
    data:
    - key: /test/302040/RDS_PASSWORD
      name: RDS_PASSWORD
    - key: /test/302040/RDS_USER
      name: RDS_USER
    region: us-east-2
    roleArn: arn:aws:iam::999999999:role/eks/role-eks-test-302040-whale-us-east-2
```

So I'm telling the controller to go assume that roleArn to grab the secret, which from step 2, you can see it will have access to do.

This is already providing "external-secrets as a service" via a controller using the GoDaddy variant; does this new variant not offer the same functionality? This link seems to imply it does: https://external-secrets.io/guides-multi-tenancy/#eso-as-a-service

We want to migrate to this new, more widely supported and feature-proofed variant, yet we don't see how that works in the current iteration.

**Comment by moolen** [comment]
Hey @dfallert-rcd  and @jbilliau-rcd 

> then how would you propose using ESO as a service with AWS IRSA?

Short answer: ESO itself should run with ZERO AWS permissions. And you create one service-account per namespace that is used in a `SecretStore`.
Long Answer: Usually we have one namespace per team (or application). This is our organisational, operational and security boundary. Every team (or app) has it's own area within secrets-manager and has only access to this particular area. This means that **for each team (or app)** you would need to create the following things:
1. an IAM Policy that allows access to a particular area to secrets-manager (e.g. by restricting by prefix, [see example](https://external-secrets.io/provider-aws-secrets-manager/#iam-policy))
2. an IAM Role that can be used by a particular namespace/service-account using IRSA
3. the Kubernetes service-account with the well-known IRSA annotation
4. A SecretStore that uses the service-account from (3)

> We have ESO in its own namespace, with its own service account and IAM role to assume other IAM roles
When using IRSA with the above mentioned set-up ESO runs with 0 AWS permissions (no IAM role, no need to assume other roles).

Thank you @jbilliau-rcd for more information about your set-up.
So, when you run ESO "privileged" (i.e. with AWS permissions through IRSA) and assume a role per team (or app) the secret is, that you don't specify the `jwt.serviceAccountRef`. Here a example:

When defining a `SecretStore` like this then ESO uses the ambient credentials provided through IRSA (because the service account token is mounted and specific env vars are set from the irsa-mutating-webhook). With these credentials ESO will do a assume-role to role `team-b`:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: team-b-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      role: team-b
```

I didn't triple check this example but it should work and if not this is a bug that will be fixed asap. We do not test this feature end-to-end as setting up the testbed is rather complex and costly, but this is on the roadmap.

As you can imagine privilege escalation is pretty easy with this approach, you can mitigate that with a policy tool like OPA/kyverno or don't allow a privileged role like that at all using the approach mentioned at the top.

**Comment by jbilliau-rcd** [comment]
Thanks for the quick response @moolen . @dfallert-rcd  is testing this now, getting rid of the `jwt.serviceAccountRef` block. It appears that the ESO controller now tries to assume our pod-specific IAM role via a role with a random "guid" at the end of it, so we are working on configured the trust policy of the pod-speicific IAM role to allow **arn:aws:sts::99999999:assumed-role/fallert-dev-99999999-us-east-2-external-secrets/***, of which **arn:aws:sts::99999999:assumed-role/fallert-dev-99999999-us-east-2-external-secrets** is the *actual* IAM role.

When you describe steps 1-4 above, and talk about IAM roles/policies/k8 service accounts, are you referring to the resources used by the **application** pod, or the **ESO** pod? We already create one namespace per app, and that application has a `ServiceAccount` created for it that is annotated with an application specific role.

So every application has it's own namespace, IAM Role and ServiceAccount, all with the right permissions to access secrets and whatever else. At this point, we just want ESO to assume that already created/working IAM role to grab the secrets, which is, again, how the GoDaddy variant worked, and worked flawlessly. We'll keep you posted on @dfallert-rcd testing of your idea. Thanks!

**Comment by dfallert-rcd** [comment]
Like @jbilliau-rcd stated above, ESO is appending a random string string of digits for the `RoleSessionName`.

After some investigation, I found that if a `RoleSessionName` is not provided, the `AssumeRoleProvider` will [use a unix timestamp](https://github.com/aws/aws-sdk-go/blob/c348111746d8e5953de52755d7c03d77708c522b/aws/credentials/stscreds/assume_role_provider.go#L308) 

Following that lead, I was lead to this repo's [auth.go](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/auth.go)

if `prov.Auth.JWTAuth` or `prov.Auth.SecretRef` are not provided, it defaults to using this 
https://github.com/external-secrets/external-secrets/blob/867006996753dbd4b96d2e8bf3e22c3d583fbcbc/pkg/provider/aws/auth/auth.go#L108-L111

namely, [`stscreds.NewCredentialsWithClient`](https://github.com/aws/aws-sdk-go/blob/c348111746d8e5953de52755d7c03d77708c522b/aws/credentials/stscreds/assume_role_provider.go#L284-L289) which doesn't support a `RoleSessionName`, and even states that the role  "will be named after a nanosecond timestamp of this operation"

I'm uncertain as to how to structure the IAM trust policy, to account for this randomly generated role name, without doing a blanket "*" allow for the principal.

**Comment by moolen** [comment]
From my experience in the past the session name usually isn't relevant for a IAM trust policy (we've always used different roles instead of specifying the session principal). You can specify the [iam role](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-roles) instead of the [specific assumed-role session principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-sessions), or do you really care about the principal?

I'm absolutely open to add a new field that allows a `SecretStore` to specify the session name.

**Comment by dfallert-rcd** [comment]
In this case I care about the principal, as I only want the ESO's assumed role to have permission to assume the role specified in the `SecretStore`. I got it to work using a wildcard principal, and conditional on the `aws:SourceArn`  like so
```
{
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "ArnLikeIfExists": {
          "aws:SourceArn": "arn:aws:sts::999999999999:assumed-role/fallert-dev-999999999999-us-east-2-external-secrets/*"
        }
      }
}
```
But I'm not the biggest fan of that, and having a distinct `RoleSessionName` would be great.    

> I'm absolutely open to add a new field that allows a SecretStore to specify the session name.

Not only having a `RoleSessionsName`, but adding a field to make it customizable would be a huge win in my opinion, and would make building trust policies simpler, as you wouldn't necessarily need to build a conditional, you could instead do something like this
```
{
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:sts::999999999999:assumed-role/fallert-dev-999999999999-us-east-2-external-secrets/my-custom-session-name"
      },
      "Action": "sts:AssumeRole"
}
```

**Comment by moolen** [comment]
Agree, i support adding that!

To make it configurable i think we can easily add a field [here](https://github.com/external-secrets/external-secrets/blob/main/apis/externalsecrets/v1alpha1/secretstore_aws_types.go#L70-L73), add an option [here](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/auth.go#L110) and specify a RoleSessionName with options ([aws docs](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/#NewCredentialsWithClient)) (plus tests 😉).

Do you feel confident to contribute that? If not can take it, but i can't guarantee when it will be finished.

**Comment by mwilliams-rcd** [comment]
@moolen I can go ahead and open a PR for @dfallert-rcd request

**Comment by mwilliams-rcd** [comment]
@moolen So digging into the issue a bit I don't believe any code change is needed (at least for what @dfallert-rcd was talking about above). The `RoleSessionName` that was causing an issue was in the base config that is generated by the AWS SDK. 

This can be resolved by setting the `AWS_ROLE_SESSION_NAME` environment variable in the ESO container. For example with the Helm chart:
```yaml
extraEnv:
- name: AWS_ROLE_SESSION_NAME
  value: my-session-name
```

Setting it here: https://github.com/external-secrets/external-secrets/blob/280964f84ea5584c4d336f8e02f8447592f7a337/pkg/provider/aws/auth/auth.go#L110 

Like so:
```golang
sess.Config.WithCredentials(stscreds.NewCredentialsWithClient(stsclient, prov.Role, func(provider *stscreds.AssumeRoleProvider){
    provider.RoleSessionName = prov.RoleSessionName
})) 
```

Will set the subsequent session name when that role is used to retrieve a value from Parameter Store/Secrets Manager. So for example if you set the new proposed value of `RoleSessionName` to `banana`:

![image](https://user-images.githubusercontent.com/72412002/132713262-7d57a6fd-d25d-4e0d-b32e-45be63ce21cb.png)

I am not exactly sure on the usefulness of that (at least off the top of my head) but if that is still something you think could potentially be valuable to someone in the future I can continue on with the PR.

**Comment by jbilliau-rcd** [comment]
For anyone else that comes across this, the specifics of what the fix was we just passed in the **AWS_ROLE_SESSION_NAME** via the helm chart `env` block to be "token-file-web-identity", which matches what the GoDaddy kubernetes-secret controller used. Thus, migrating from that one to this one now seems trivial and painless. Score!

**Comment by moolen** [comment]
> I am not exactly sure on the usefulness of that (at least off the top of my head) but if that is still something you think could potentially be valuable to someone in the future I can continue on with the PR.

It is potentially valuable IMO, PRs are definitely welcome. But there's no immediate need as far as i can tell. From my past experience i've never seen the role-session-name used in a policy.

Thanks for digging and documenting the issue here ❤️. Can we close this now, or are any things left to do?

**Comment by mwilliams-rcd** [comment]
I don't believe there is anything left to do and this can be closed. I will PR my changes in anyway since they are already done. 😄
