### ISSUE TITLE
SonarCloud CodeSmells

### ISSUE THREAD

**Issue by Ed-vL** [external-secrets/external-secrets#416]
**Describe the solution you'd like**
Opening an issue to track SonarCloud code smells to fix. I am gonna send a comment next in this issue to let everyone know what code smells I will be working on. Please do the same if you are planning to grab some :)

**What is the added value?**
Fixing some code smells will enhance the overall code quality and health

**Comment by omateusp** [comment]
I'll work on these:

at `pkg/controllers/externalsecret/externalsecret_controller.go`:
- [ ] Refactor this method to reduce its Cognitive Complexity from 27 to the 15 allowed.

at `pkg/provider/aws/secretsmanager/secretsmanager_test.go`:
- [ ] Define a constant instead of duplicating this literal "[%d] unexpected error: %s, expected: '%s'" 3 times.

at `pkg/provider/aws/auth/auth_test.go`:
- [ ] Define a constant instead of duplicating this literal "es-namespace" 3 times.
- [ ] Define a constant instead of duplicating this literal "platform-team-ns" 3 times.
- [ ] Define a constant instead of duplicating this literal "my-service-account" 4 times.
- [ ] Define a constant instead of duplicating this literal "other-ns" 4 times.

at `pkg/provider/schema/schema_test.go`:
- [ ] Define a constant instead of duplicating this literal "provider should be registered" 3 times.

**Comment by Git-Jiro** [comment]
Hi @Ed-vL,
I would like to work on some of those code smells.
Where do I find the code smell reports of SonarCloud?
