### ISSUE TITLE
**BREAKING CHANGE FOR v0.11.0** Problem Thread

### ISSUE THREAD

**Issue by Skarlso** [external-secrets/external-secrets#4167]
## Kubernetes API load and significant decrease

A new way of reconciling external secrets has been added with pull request #4086.

This significantly reduces the number of API calls that we make to the kubernetes API server.

1. Memory usage might increase if you are not already using `--enable-secrets-caching`
    1. If you are using `--enable-secrets-caching` and want to decrease memory usage at the expense of slightly higher API usage, you can disable it and only enable `--enable-managed-secrets-caching` (which is the new default)
2. In ALL cases (even when CreationPolicy is Merge), if a data key in the target Secret was created by the ExternalSecret, and it no longer exists in the template (or data/dataFrom), it will be removed from the target secret:
    1. This might cause some peoples secrets to be "cleaned of data keys" when updating to 0.11.
    2. Previously, the behaviour was undefined, and confusing because it was sort of broken when the template feature was added.
    3. The one exception is that ALL the data suddenly becomes empty and the DeletionPolicy is retain, in which case we will not even report and error, just change the SecretSynced message to explain that the secret was retained.
3. When CreationPolicy is Owner, we now will NEVER retain any keys and fully calculate the "desired state" of the target secret each loop:
    1. This means that some peoples secrets might have keys removed when updating to 0.11.

## Generators and ClusterGenerator

We added ClusterGenerators and Generator caching as well. This might create some problems in the way generators are defined now.

## CRD Admission Restrictions

All of the CRDs now have proper kubebuilder markers for validation. This might surprise someone leaving out some data that was essentially actually required or expected in a certain format. This is now validated in #4104.

**Comment by onedr0p** [comment]
I wanted to chime in and say I've updated to this and haven't noticed any problems yet. Thanks for the QoL updates.

**Comment by joryirving** [comment]
Updated to 0.11.0, and ran into the stated `Merge` issue. I currently have 2 secret stores, and use the merge function to create a single secret, and am no longer able to do that. 

```
external-secrets  unable to mutate secret bazarr-secret: secret is owned by another ExternalSecret: example-secret
```
This is one of my examples: https://github.com/joryirving/home-ops/blob/9397f136b13559c52790cbb29bc5751fea6e7328/kubernetes/main/apps/self-hosted/paperless/app/externalsecret.yaml
Is there a known fix or workaround for this?

**Comment by thesuperzapper** [comment]
>  Updated to 0.11.0, and ran into the stated `Merge` issue. I currently have 2 secret stores, and use the merge function to create a single secret, and am no longer able to do that. 
> 
> ```
> external-secrets  unable to mutate secret bazarr-secret: secret is owned by another ExternalSecret: example-secret
> ```
> This is one of my examples: https://github.com/joryirving/home-ops/blob/9397f136b13559c52790cbb29bc5751fea6e7328/kubernetes/main/apps/self-hosted/paperless/app/externalsecret.yaml
> Is there a known fix or workaround for this?

@joryirving remember that the default `creationPolicy` is `Owner`. You need to explicitly set all the external secrets which target the same secret to `Merge`.

In your example, you are actually using `creationPolicy` = `Owner` on the secret which you didn't set a creationPolicy for.

Since 0.11, we now detect these cases and only reconcile the first owner ExternalSecret we see, otherwise we would end up in a loop of updates and reversion.

**Comment by joryirving** [comment]
Will `Merge` create the secret if it doesn't exist?

**Comment by thesuperzapper** [comment]
> Will `Merge` create the secret if it doesn't exist?

@joryirving no, it will not, but it will detect when the secret is created and immediately reconcile.

So you can just include a "blank" version of the secret (as long as your system won't remove keys) when you re-apply that "blank" one.

**Comment by joryirving** [comment]
Everything is setup via gitops. I'm assuming if I include a blank secret, flux will reconcile and overwrite it. This currently works as expected in 0.10.7, where the first secret creates it, and the second one merges the values. There appears to be no loop, as `reloader` would be constantly reloading pods.

**Comment by thesuperzapper** [comment]
You could also simply combine your two ExternalSecrets into a single "owner" one, using the ability to use multiple SecretStores within the same ES.

**Comment by joryirving** [comment]
You can do that? Is there an example?

**Comment by gusfcarvalho** [comment]
@thesuperzapper this breaking change is inherent of us changing the `patch` operation with `update`, right?

As in, would this effectively even break two ExternalSecrets with Merge Policies (as they would also collide for Updates)?


If not, can't we just filter the error message for targetting `CreationPolicy = Owner` as well?

**Comment by gusfcarvalho** [comment]
> You can do that? Is there an example?

It is very specific for some APIs in ExternalSecrets. Your specific use case would allow it:
```
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name paperless-secret
spec:
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: '{{ index . "pgbouncer-port" }}'
        PAPERLESS_DBNAME: '{{ .dbname }}'
        PAPERLESS_DBHOST: '{{ index . "pgbouncer-host" }}'
        PAPERLESS_DBUSER: '{{ .user }}'
        PAPERLESS_DBPASS: '{{ .password }}'
        # App
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "{{ .PAPERLESS_CLIENT_ID }}",
                        "secret": "{{ .PAPERLESS_CLIENT_SECRET }}",
                        "settings": {
                            "server_url": "https://sso.${SECRET_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
  dataFrom:
  - extract:
      key: paperless
     sourceRef:
       secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: postgres-pguser-paperless
     sourceRef:
       secretStoreRef:
          name: crunchy-pgo-secrets
          kind: ClusterSecretStore

**Comment by joryirving** [comment]
Well that's fantastic and saves me a ton of code. Thank you!

**Comment by tculp** [comment]
A few issues with immutable secrets have been fixed (e.g. https://github.com/external-secrets/external-secrets/issues/3919 and https://github.com/external-secrets/external-secrets/issues/3920), but it seems a new issue has been introduced: immutable secrets will always get to Status: SecretSyncedError and Ready: False.

Maybe a new status should be created, such as ImmutableSecretSkipped.

```
status:
  binding:
    name: example-secret
  conditions:
  - lastTransitionTime: "2024-12-03T18:36:39Z"
    message: could not update secret, target is immutable
    reason: SecretSyncedError
    status: "False"
    type: Read
```

**Comment by gusfcarvalho** [comment]
> A few issues with immutable secrets have been fixed (e.g. #3919 and #3920) (thanks btw), but it seems a new issue has been introduced: immutable secrets will always get to Status: SecretSyncedError and Ready: False, even when no attempted changes have been made
> 
> Maybe a new status should be created, such as ImmutableSecretSkipped.
> 
> ```
> status:
>   binding:
>     name: example-secret
>   conditions:
>   - lastTransitionTime: "2024-12-03T18:36:39Z"
>     message: could not update secret, target is immutable
>     reason: SecretSyncedError
>     status: "False"
>     type: Read
> ```
> 
> This is really more of a minor inconvenience since the behavior with immutable secrets works as expected now, only the status is confusing.

Errors are expected here - immutable secrets should never be updated.

if you try creating an ES with immutable secrets and refreshInterval of 0 you should never see this error

**Comment by tculp** [comment]
The refreshInterval of 0 helped, but there's still one situation where the error appears: Creating an immutable secret with `creationPolicy: Orphan`, then deleting and recreating the externalSecret

**Comment by thesuperzapper** [comment]
> @thesuperzapper this breaking change is inherent of us changing the `patch` operation with `update`, right?
> As in, would this effectively even break two ExternalSecrets with Merge Policies (as they would also collide for Updates)?

@gusfcarvalho It's not about the internal implementation, it's just that we don't allow multiple ExternalSecrets to be the `Owner` of the same target. This is not a new thing for 0.11, previously, we would just error loop rather than detecting it and making the SyncStatus error.

As long as all the ExternalSecrets which target a Secret use `Merge` policy, everything will be fine.

---

However, I note that the behavior or `Orphan` is now the same as Owner (just without the OwnerReference being set). That is, all changes/keys not from the ExternalSecret will be removed every refresh. 

So, if two `Orphan` ExternalSecrets try to manage the same target Secret, so they will just loop. The problem is that there is no "safe" way to know that this is happening and put both into an error, because the whole idea of `Orphan` is that we can delete the ES and not remove the target secret. 

So we will probably just need to highlight that users should be careful with "orphan".

**Comment by thesuperzapper** [comment]
> The refreshInterval of 0 helped, but there's still one situation where the error appears: Creating an immutable secret with `creationPolicy: Orphan`, then deleting and recreating the externalSecret.
> 
> I admit this is a bit of a niche case, but it's a scenario I expect to encounter. (Using fluxCD to generate a password, which we want to be immutable so it doesn't ever change, but we may want to delete and recreate the fluxCD resources)

@tculp the reason this is an "error" is that each ExternalSecret wants to be synced at least once (even those with `refreshInterval=0`, but because the target secret already exists and is immutable, it is unable to sync it that first time.

The problem is that there is no way to know if the parameters are exactly the same as the old ExternalSecret which generated the target, so it's correct for it to be an "error".

It probably makes more sense to use `creationPolicy=Owner` so the target secret is cleaned up when the ExternalSecret is deleted so if its re-applied it will regenerated a new random password.

**Comment by gusfcarvalho** [comment]
Also related to `0.11.0`: https://github.com/external-secrets/external-secrets/issues/4172

**Comment by gusfcarvalho** [comment]
> As long as all the ExternalSecrets which target a Secret use Merge policy, everything will be fine.

wouldn't there be any impact to have a ExternalSecret with `Owner` + N ExternalSecrets with `Merge` creation policies in this case, then?

**Comment by gusfcarvalho** [comment]
> The refreshInterval of 0 helped, but there's still one situation where the error appears: Creating an immutable secret with `creationPolicy: Orphan`, then deleting and recreating the externalSecret.
> 
> I admit this is a bit of a niche case, but it's a scenario I expect to encounter. (Using fluxCD to generate a password, which we want to be immutable so it doesn't ever change, but we may want to delete and recreate the fluxCD resources)

Do you need the password to be the same even when you recreate Flux resources? Or re-generating it like @thesuperzapper mentioned would be acceptable?

The direction we want to move forwards here is not use immutable secrets to avoid regeneration. As of `0.11.0`, just setting `creationPolicy: Owner` and `refreshInterval:  0` will already make sure the generated secret is only re-generated in case it is destroyed.

☝️ would that be a pattern applicable to you @tculp ?

**Comment by tculp** [comment]
@gusfcarvalho That doesn't really solve my use case, which I'll describe as follows.

We use the grafana operator to control a grafana instance. We need to be able set the admin user's password, and we currently do this with a secret, which is set upon creation. However, the admin password does not get updated by the operator even if the secret changes.

When logging in, we retrieve the secret using kubectl from the cluster. Thus we need the secret in the cluster to be the source of truth. If the secret in the cluster is regenerated, then we lose the ability to check the password by looking at the secret, and we no longer have a good way of retrieving it without manually copying the initial secret to another location. So we **really** want to minimize the likelihood of the secrets getting regenerated. The only time we would want the secret to be regenerated is if we manually force it by deleting the Secret.

A push secret to push the password to an external system like AWS secrets manager also doesn't really help because that also overrides if it's regenerated and secrets manager doesn't maintain all versions of a secret

**Comment by thesuperzapper** [comment]
> @gusfcarvalho That doesn't really solve my use case, which I'll describe as follows.
> 
> We use the grafana operator to control a grafana instance. We need to be able set the admin user's password, and we currently do this with a secret, which is set upon creation. However, the admin password does not get updated by the operator even if the secret changes.

@tculp Then just use an immutable `ExternalSecret` with `refreshInterval: 0`, and `creationPolicy: Owner`, then include this in your Grafana flux app (so that it will only be deleted when you re-install flux).

I you for some reason want to delete your Grafana and keep the same password when you re-install it, then just add the `kustomize.toolkit.fluxcd.io/prune: disabled` annotation to your ExternalSecret.

> Our current solution is to generate random passwords with Terraform and then create kube secrets from those, but we would like to adopt a more automatic and eventually-consistent workflow.

This is also a valid way to do it, but I am not clear how terraform is involved if you are using FluxCD, I assume only to trigger it?

**Comment by tculp** [comment]
@thesuperzapper I think disabling flux pruning in combination with the refreshInterval and immutable is probably the combination that'll get me what I need. I'll try it out. Thanks!

**Comment by Skarlso** [comment]
You have `refreshInterval` set to `0`. Can you try setting it to some other value and see if that works?

**Comment by RytisBa** [comment]
We tried changing it as well as recreating our external secret/store, the issue persisted. 

For context, our workflow is creating ExternalSecret resource with Helm hooks so each time a new release is made, we delete ExternalSecret and recreate it, that is why the refreshInterval is set to 0 as we don't want to hit Gitlab API for nothing (the only time the secret value would change or be added is before the release happens).

**Comment by Skarlso** [comment]
hmm, interestingly enough this part of the code was not touched in over 2 years. :D 

Can you confirm that if you revert back it's still working please? 🤔

**Comment by thesuperzapper** [comment]
@Skarlso what about this commit, which changed the error handling: https://github.com/external-secrets/external-secrets/commit/b518bae15fe8a6d4287c6aa6f59d897fd785337d

**Comment by Skarlso** [comment]
Ugh, you're right. I removed the error != nil check but there was a subtle difference that it actually didn't error in case the status code was not found. In that case it proceeded with groupids.

I'll fix it.

**Comment by gusfcarvalho** [comment]
I think this issue is now safe to close 😄

**Comment by Skarlso** [comment]
Thank you all for your comments. Please feel free to open any new issues you find.

**Comment by aprat-mentaia** [comment]
Hello, I tested version 0.12.1 and I still have the issue with variable groups. I also tested with 0.10.7, and it works fine. 
Are you sure it's fixed ?

Thank you!

**Comment by Skarlso** [comment]
Could you remind me what issue that is? Thanks.

**Comment by Baune8D** [comment]
We experience ExternalSecret's not updating when changing spec if `refreshInterval` is 0.

This worked before 0.11.0. Is this expected behaviour?

**Comment by Skarlso** [comment]
That's excepted behaviour... You set the interval to 0. Meaning DON'T refresh. Right?

**Comment by Baune8D** [comment]
> That's excepted behaviour... You set the interval to 0. Meaning DON'T refresh. Right?

My understading was that `refreshInterval: 0` would prevent the external secret from poll for updates values. Not that it would prevent manual updates of a secret version.

**Comment by Skarlso** [comment]
Errr.. what? :D Which secret version are you talking about here?

**Comment by Baune8D** [comment]
> Errr.. what? :D Which secret version are you talking about here?

Take this secret for example:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: worker-dropbox-gcp-secrets
  namespace: exporter
spec:
  data:
  - remoteRef:
      key: Some_secret
      version: "1"
    secretKey: Some_secret
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
```

Before 0.11.0 we could update `spec.data.remoteRef.version` and the new version would be synchronised as expected.

Post 0.11.0 nothing happens unless we set `refreshInterval` to some other value than 0.

We use Google Secret Manage btw.

**Comment by gusfcarvalho** [comment]
This is indeed expected. As from 0.11.0, this is the behavior of refreshInterval: 0.

**Comment by Baune8D** [comment]
> This is indeed expected. As from 0.11.0, this is the behavior of refreshInterval: 0.

Thanks for clarifying. I do find this behaviour quite confusing when compared to the documentation:

<img width="657" alt="image" src="https://github.com/user-attachments/assets/04280a04-df7f-4f99-bb2b-73a9ffc4c7d8" />

**Comment by Skarlso** [comment]
It's saying "set to zero to fetch and create _once_". Do you have a better sentence to describe that it's not going to touch it again?

**Comment by gusfcarvalho** [comment]
> > This is indeed expected. As from 0.11.0, this is the behavior of refreshInterval: 0.
> 
> Thanks for clarifying. I do find this behaviour quite confusing when compared to the documentation:
> 
> <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/30204280/401275693-04280a04-df7f-4f99-bb2b-73a9ffc4c7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNzk2MTcsIm5iZiI6MTczNjM3OTMxNywicGF0aCI6Ii8zMDIwNDI4MC80MDEyNzU2OTMtMDQyODBhMDQtZGY3Zi00Zjk5LWJiMmItNzNhOWZmYzRjN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDIzMzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMDcyMDBhMmRjOTRlZTA1OGNjMGEzMTFlYTQzMTc0M2VhNDRiZmRmMWNhNTE3NGU4YTQ5N2UxZDc1ODA3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1MCeuSYiq-3MlJXlWg33myPJu0slrBFwj3dZxpNabqI">
> I would expect `refreshInterval: 0` to just disable automatic updates.

If documentation is confusing, this can be treated in another PR. In any case, the behavior pre 0.11 changed, and it is a breaking change for use cases (including yours most likely @Baune8D). My suggestion for your use case is to set a high (but not zero) refresh Interval such as `10000h`

**Comment by Skarlso** [comment]
Yeah I meant to say if you a better way of phrasing please feel free to change it. I will gladly review it. 😊 Reading back I sort of sounded aggressive but this was not intended. 😆

**Comment by Baune8D** [comment]
> Yeah I meant to say if you a better way of phrasing please feel free to change it. I will gladly review it. 😊 Reading back I sort of sounded aggressive but this was not intended. 😆

No worries, i understand 😄 I will try to explain a bit more what confused our team about this.

The inital explanation about `refreshInterval` is:

> RefreshInterval is the amount of time before the values are read again from the SecretStore provider.

Based on the name of the property being `refreshInterval`, and the above explanation, for me this seems to indicate that the property is about refreshing the secret after manifest deployment, and not that it is related to what happens when the manifest is updated since this is not related to an interval value. I read the sentence `set to zero to fetch and create once` as describing that ESO will not update the secret by itself after manifest is created/updated.

Also we can find this in the documentation:

<img width="590" alt="image" src="https://github.com/user-attachments/assets/a4bec9f1-5324-4fc5-9835-46762fead8eb" />

I read this as an OR list, so reading this i would expect the secret to update when the spec is changed, even though `refreshInterval` is 0.

**Comment by Skarlso** [comment]
@aprat-mentaia Interesting, I thought I fixed that problem in https://github.com/open-component-model/ocm/issues/1214.

**Comment by aprat-mentaia** [comment]
Yes, I saw that, which is why I'm asking if the issue has truly been fixed. When I use helm chart v0.12.1, I get a '404 Not Found' error when fetching the group variables, but it works fine with v0.10.7. My configuration is similar to RytisBa.

**Comment by Skarlso** [comment]
I'll take a look.

**Comment by Skarlso** [comment]
@aprat-mentaia what is the error string you are getting?

**Comment by aprat-mentaia** [comment]
@Skarlso "error processing spec.data[0] (key: ACCESS_SECRET_KEY), err: 404 Not Found"

**Comment by Skarlso** [comment]
I can't find anything that is related to this problem. Can you show your ES?
