### ISSUE TITLE
Question: Install ESO via OLM (Operator Lifecycle Manager)?

### ISSUE THREAD

**Issue by slopezz** [external-secrets/external-secrets#493]
**Describe the solution you'd like**

It would be awesome if ESO could be integrated into [OLM](https://olm.operatorframework.io/), which is a marketplace for k8s operators, so for example ESO would be available at [OperatorHub.io](https://operatorhub.io/) (by submitting the operator on both [k8s](https://github.com/k8s-operatorhub/community-operators) and [OpenShift](https://github.com/redhat-openshift-ecosystem/community-operators-prod) catalogs). 

**What is the added value?**

Helm is OK to manage simple k8s application installation, but when working with k8s operators, you need to manage operator lifecycle, upgrades, patches... OLM makes easier to manage the whole operator lifecycle at scale.

With OLM the operator installation can be done within a couple of clicks via UI, or with a few custom resources like OLM OperatorGroup and Subscription, that can be easily integrated into GitOps workflows with tools like ArgoCD on a declarative way without having to execute dynamic commands like `helm install ...`.

**Give us examples of the outcome**

Most of current cloud native applications has k8s operators already on OLM (etcd, prometheus, grafana, vault, argoCD, flux, cert-manager, istio, knative...). 

Some of them are even helm operators, `operator-sdk` framework has the [operator-sdk helm version](https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/), theoretically it should easy to convert current helm charts into operators that can easily be integrated into OLM.

**Observations (Constraints, Context, etc):**

None.

**Comment by knelasevero** [comment]
@sevikarakose  @onselakin

**Comment by slopezz** [comment]
As we needed to install the current **external-secrets** helm-chart operator via OLM, we have created a kind of new *meta* operator using [operator-sdk](https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/#use-an-existing-chart), that is in charge of deploying current helm chart.

We have published it at https://github.com/3scale-ops/external-secrets-operator

Although the solution is not perfect (it could be better integrated into OLM, if for example CRDs were managed by OLM instead of being created by the operator), is the easiest way we have found to make usage of current helm-chart on a OLM way. It does not require any change on current helm-chart, making the maintenance easy by just updating the helm chart version on a Makefile, and executing an automated release pipeline with a GitHub action.

**Comment by moolen** [comment]
Awesome @slopezz! We've wanted to support OLM for a while (#244). Your helm-based implementation looks very promising - i particularly like the ability to customize the installation with the embedded `values.yaml` file. 

We want to provide and maintain a package of our operator in both the [community-operators](https://github.com/k8s-operatorhub/community-operators) and [openshift](https://github.com/redhat-openshift-ecosystem/community-operators-prod) space. I think it makes sense to couple the `olm bundle` process to the ESO release process so that every ESO release will publish a new bundle.
Do you think it makes sense to move your repo to the `external-secrets` org and we take care of bundling and releasing both helm and OLM artifacts?

Reminder to myself: flux2 has a different approach. They [generate the bundle files](https://github.com/weaveworks/flux2-openshift) with a couple of scripts which may be an alternative (though not very configurable for the user)

**Comment by slopezz** [comment]
Sure @moolen, we are happy to transfer the repo to `external-secrets` org, so you could maintain both helm and OLM artifacts together (for the moment we are using our own OLM catalog managed with the repo with images on `quay.io`, so we can install it with OLM until you publish it on OperatorHub).

As I mentioned on my previous comment, the current implemented solution is not perfect, because the helm-chart is in charge of managing the CRDs, which is not safe as long as if you remove the `OperatorConfig` custom resource (so you delete the helm-char-operator managing CRDs) while there are many `ClusterSecretsStore`, `SecretStore` and `ExternalSecrets` deployed in the cluster, you might break all those resources with a deleted CRD.

Ideally, the CRDs management should be moved to OLM bundle files (like any other CRD), because with OLM, if you uninstall an operator, nothing happen to your current deployed custom resources (100% safe), because CRDs are not removed from the cluster.

I've seen there there is already a helm-chart var to not manage CRDs (by default `installCRDs: true`), and I've seen that with **operator-sdk helm version**, you can always override helm vars:
https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/override_values/#basic-usage
![image](https://user-images.githubusercontent.com/41513123/144224645-94de67cc-c8c9-430f-bb44-7d6e322baed7.png)

So maybe it could be added in the operator `watches.yaml`:
```yaml
# Use the 'create api' subcommand to add watches to this file.
- group: operator.external-secrets.io
  version: v1alpha1
  kind: OperatorConfig
  chart: helm-charts/external-secrets
  overrideValues:
    installCRDs: false
#+kubebuilder:scaffold:watch
```

And move the CRDs management to the OLM bundle files.

**Comment by moolen** [comment]
FYI: I experimented a bit with the flux approach to generate the `ClusterServiceVersion` manifest. However it's not possible to configure / apply patches to the OLM deployment. That means we can't even add annotations to service accounts or modify env vars in the deployment. This limits our users too much and i think it's a way better approach to have a operator that simply runs `helm install` with user-defined values. 
I made some changes to the external-secrets-operator to make it possible to generate a `bundle` (instead of creating own images/catalog). I'll open a PR there soon.  

For reference / my olm-generator branch: https://github.com/moolen/external-secrets/tree/experimental/olm-packaging/deploy/olm
