### ISSUE TITLE
Does external-secrets support type: kubernetes.io/tls ?

### ISSUE THREAD

**Issue by themarcelor** [external-secrets/external-secrets#599]
Just seeking some general guidance:
Looks like some documentation / examples reference an `ExternalSecret` CRD with `apiVersion: kubernetes-client.io/v1` but the CRD that is installed through the helm chart actually contains `external-secrets.io/v1alpha1`, which results in an error:
```
no matches for kind "ExternalSecret" in version "kubernetes-client.io/v1"
```

I have been using the `external-secrets` whose Helm chart was installed by following the instructions in https://external-secrets.io/guides-getting-started/
However, this one does not seem to support TLS type secrets 🤔 (or maybe I couldn't find the appropriate documentation for that).

Looks like `kubernetes.io/tls` is only supported in:
https://github.com/external-secrets/kubernetes-external-secrets
but not in
https://github.com/external-secrets/external-secrets

Is there any documentation clarifying the difference between these two projects? (beyond the fact they're implemented in different languages? 🤷🏼 ).

I'm trying to conduct an experiment with:
```
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  target:
    name: my-tls-secret
```

Any pointers are appreciated.

**Comment by moolen** [comment]
Hey @themarcelor. You can find examples on how to use the secret type [here in the docs](https://external-secrets.io/guides-common-k8s-secret-types/#tls-cert-example).

`kubernetes-external-secrets` aka `KES` is the "old" controller. `external-secrets` aka `ESO`. Lucas has a twitter thread on that: https://twitter.com/canelasevero/status/1365233452229013505. KES is in maintenance mode and we focus on the rewrite here.

Anyways, the issue here is that you're mixing the two worlds: You're applying a KES Resource when actually using the ESO controller.

**Comment by themarcelor** [comment]
Thanks a million @moolen 🙏🏼 😄
