### ISSUE TITLE
Fix helm chart  install 

### ISSUE THREAD

**Issue by ckandag** [external-secrets/external-secrets#67]
The helm chart install as documented here is failing with this error 
Installing the chart as documented [here](https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets)   fails with the below error

 `% helm repo add external-secrets https://external-secrets.github.io/external-secrets 

Error: looks like "https://external-secrets.github.io/external-secrets" is not a valid chart repository or cannot be reached: failed to fetch https://external-secrets.github.io/external-secrets/index.yaml : 404 Not Found`

Tried installing the chart directly from the chart source and ran into the below with default values

Failed to pull image "ghcr.io/external-secrets/external-secrets:0.1.0": rpc error: code = Unknown desc = Error reading manifest 0.1.0 in ghcr.io/external-secrets/external-secrets: name unknown

**Comment by ckandag** [comment]
unable to self assign this.

**Comment by mcavoyk** [comment]
This is because the chart repo has not been setup and there has been no initial release. The only way to install the chart at the moment is to build locally, can run `helm install external-secrets ./deploy/charts/external-secrets/` or `helm package ./deploy/charts/external-secrets/` after cloning.

We are planning on an initial release after a few more of the core providers are added, like Hashicorp Vault, and GCP. Although we should set up the helm repo before then and begin to add helm builds from main branches.

**Comment by jonatasbaldin** [comment]
Related to #105.
