### ISSUE TITLE
Delete Secret keys or the Secret altogether when they are deleted in the external provider

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#695]
From a compliance perspective, users may want to trigger batch deletions to mitigate breaches or any other security issues. Right now when we delete secrets in the external providers, the reconciliation loops fails but the secret inside the cluster is not deleted.

A workaround that people can use now is to insert junk into the external provider secret, but this is sub-optional.

**Comment by moolen** [comment]
We can check for specific errors in the `provider` and do cleanup action in the controller:
* aws parameter store: we can check for [ParameterNotFound](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#ParameterNotFound) and delete if needed
* aws secrets manager: [SecretNotFoundException](https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#ResourceNotFoundException)
* gcp SecretManager `NOT_FOUND` grpc error code
* azure: 404 status code should be embedded in the error type
* vault: use http status code 404

#### deletionPolicy=Delete
if the provider returns no data (via `data` or `dataFrom`) the `Kind=Secret` must be deleted.
With `creationPolicy=Merge` or `creationPolicy=None` we are not allowed to do that. This is a configuration error and must be caught in the `Validate()` step.

#### deletionPolicy=Merge
We do a diff using `metadata.ManagedFields` with the data from the provider and the data from the `Kind=Secret`.
There is no point in using `creationPolicy=None` because it is a noop. This is a configuration error and must be caught in `Validate()`.

#### deletionPolicy=None
If the provider returns no data then nothing happens with the `Kind=Secret`. This is the current/default behavior.

FYI: I have a draft with some of the above requirements implemented: https://github.com/external-secrets/external-secrets/tree/feature-delete-policy. I don't know when i have the time to finish it tho.

**Comment by artem-nefedov** [comment]
Would be great to also implement a policy that allows Secret to always be preserved (regardless of data returned from the provider), as mentioned in #497
