### ISSUE TITLE
Investigate plugin functionality

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#696]

**Comment by knelasevero** [comment]
Hey

https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension

Kube-scheduler is investigating using wasm to extend functionality. I think we could do the same (investigate).

https://github.com/kubernetes/kubernetes/issues/112851#issuecomment-1549697076

**Comment by sagikazarmark** [comment]
I'm facing the same problem at @dexidp and @bank-vaults, but I guess this is an ecosystem-wide problem.

So I'm signing up for notifications on this issue, but I'm also happy to collaborate if I find the time to explore some of the available options.

**Comment by knelasevero** [comment]
You mean having a bunch of sidecar containers as the plugins?

**Comment by knelasevero** [comment]
You make a case against wasm but at the end lists a few efforts that are being pushed forward 😅 is the idea for us to avoid it as it currently doesn't deliver what we want, but still keep them under our radar to see if eventually things align?

**Comment by knelasevero** [comment]
Also, why hashicorp go plugin is a dead end?

**Comment by moolen** [comment]
> You make a case against wasm but at the end lists a few efforts that are being pushed forward

I just want to share the links here, if someone is interested, or if someone comes back later to this thread to re-investigate.

> keep them under our radar to see if eventually things align

Once it has become stable we can consider moving towards it. It has a smaller attack surface (less syscalls), but apart from that it doesn't provide much value :shrug: You can make arguments for and against it, but at this point in time i don't see that it's a good investment of our time: need to fix lots of stuff upstream, test the runtime and syscall interfaces, fix SDKs etc.

> Also, why hashicorp go plugin is a dead end?

It's not built to run on a fixed socket address. It starts a unix listener in the `tmp` dir. There is a way to get the path to it, but this is designed to be used in a `test` setup/environment. It's not something that is intended to be used in a production environment.

You can "make it work" with a couple of workarounds, but i think we're better off to build something for our specific use-case.  

WRT: https://github.com/hashicorp/go-plugin/issues/165

**Comment by moolen** [comment]
I have a PoC on this branch: https://github.com/external-secrets/external-secrets/tree/mj-provider-mod But this is still far far from being alpha grade. I was able to get e2e tests for AWS Secrets Manager, AWS Parameter Store and Vault going while using a fat Pod where each provider runs in a dedicated container.

**I don't have any plans to further progress on this due to this feature being deprioritised.** Still i want to document what has been done, what needs improvement:

1. build an additional `providerless` binary using go build tags that doesn't include any provider code
    1. Note: the `pkg/generator` tree still has still dependencies on provider-specific SDKs. This has to be migrated/factored out eventually
1.  build a fat container that contains all the binaries: `external-secrets-${arch}`, `external-secrets-${arch}-providerless` and all 15 `provider-${name}` binaries which can be invoked separately
1. generate `provider` shell (`pkg/remote/shell`) that hosts the provider-specific code  and offers a unix domain socket API to allow ESO to interact with the provider using GRPC.
1. build an adapter on the ESO side to replace the existing provider registration mechanism and forward `GetSecret()` calls to the provider via UDS. This is done by naming convention: `unix:///var/run/eso/provider/sockets/${provider-name}.sock`.
1. I've implemented a way to let ESO "guess" what `Kind=Secrets` or `Kind=ConfigMaps` are needed on the provider side (ideally, it shouldn't have access to control-plane) by using reflection and looking for specific types `v1.SecretKeySelector`, `v1.ServiceAccountSelector` or `metav1.CAProvider`. These resources are fetched by ESO and transmitted via UDS to the provider.
1. From a user perspective you need to override the ESO container entrypoint to `/bin/external-secrets-providerless` and create provider containers. This has been implemented in the helm chart like this:

```yaml
providers:
  sidecar:
    enabled: true
    providers:
    - aws
    - gcp
    - vault
    - webhook
    # TODO: add shared provider container settings like
    # securityContext and others
```

Risks & Challenges:
1. If we move towards this approach outlined above (or a similar one) and commit to it we eventually should deprecate our current approach (using in-tree providers) due to the **complexity of maintaining both**. Even adding this new approach will result in lots of support questions, documentation needs, FAQs, upgrade path etc.
2. Some providers (alibaba RRSA auth, IBM) rely on mounted files for authentication. The upgrade path is, from a user perspective, quite tedious, as this is not a drop-in replacement and it needs to be configured and tested properly.

**Comment by knelasevero** [comment]
Having out of tree plugins only benefits us, in my opinion, if we can have other people maintain their plugins. I don't want to have an AWS plugin out of tree and have us maintain it. If we have an AWS plugin out of tree, people will consider this having more value if AWS folks maintain it (as we see with sscsid and some other projects with these approaches)

**Comment by hypery2k** [comment]
are there any news on that discuss? In our current project we built our own operator for generating MS SQL users dynamic.

Would be great to have this as plugin added to ESO

**Comment by evrardj-roche** [comment]
See also: https://github.com/external-secrets/external-secrets/issues/5218
