### ISSUE TITLE
[Compliance] FIPS and Base image

### ISSUE THREAD

**Issue by IdanAdar** [external-secrets/external-secrets#829]
### Discussed in https://github.com/external-secrets/external-secrets/discussions/828

<div type='discussions-op-text'>

<sup>Originally posted by **IdanAdar** March 15, 2022</sup>
Can ES baseline change to use scratch or UBI as base image, to also comply with FIPS requirements for financial services and FedRAMP?</div>

**Comment by moolen** [comment]
Hey @IdanAdar you're talking specifically about `FIPS 140–2`, right? We surely can use FIPS compliant modules but we probably don't aim for a FIPS certification (for $$ reasons). 

AFAICT it's not enough to change the base image we would also have to create a static binary with boringssl in order to be compliant. (there's a `goboring` builder image iirc).

**Comment by IdanAdar** [comment]
ESO now offers UBI image variant, which we will update to use go-toolset once it is provided with Go 1.18. Closing.
