### ISSUE TITLE
Compatibility with K8 version

### ISSUE THREAD

**Issue by minnie-jeong-otsk** [external-secrets/external-secrets#857]
The documentation should contain Compatibility Matrix with K8s.
It is required when we walk through the service impact analysis before upgrading the K8 cluster.
As I look through the doc, I couldn't find one. If there already exists, please let me know.

**Comment by knelasevero** [comment]
You just need kubernetes to be over 1.11. Nothing else to consider.

https://github.com/external-secrets/external-secrets/blob/d0a32b6f2dbb1718d862c00915131522b1572c9a/deploy/charts/external-secrets/Chart.yaml#L7

**Comment by knelasevero** [comment]
Closing this one, feel free to re-open/comment :)

**Comment by moolen** [comment]
I think the idea is to have a compatibility matrix in the docs like so (e.g. like [external-dns](https://github.com/kubernetes-sigs/external-dns#kubernetes-version-compatibility) or [ingress-nginx](https://github.com/kubernetes/ingress-nginx/#support-versions-table)):

| ESO Version  | Kubernetes Version  |
|---|---|
| 0.5.x  | 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23  |
| 0.4.x  | 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23  |
|  0.3.x |  ... |

Actually, Kubernetes 1.16+ is required due to the fact that we use `admissionregistration.k8s.io/v1` for validation webhook and `apiextensions.k8s.io/v1` for CustomResourceDefinitions.

**Comment by knelasevero** [comment]
So sorry, that's right! But saying that we need 1.16+ is sufficient anyways and a matrix is just noise, no? Also, we need to update that in the chart then, right?

**Comment by minnie-jeong-otsk** [comment]
Sorry to jump in, my intention was what moolen said. But if there's no need for matrix for now, I think you can state that 1.16+ is sufficient in the doc. But as an example of [ingress-nginx](https://github.com/kubernetes/ingress-nginx/#support-versions-table), if there's an end of support for certain k8s version, it'd be better to use matrix to avoid any confusions.

**Comment by knelasevero** [comment]
There they have a matrix because they are showing more than just kubernetes versions (alpine image version and nginx version itself).

**Comment by minnie-jeong-otsk** [comment]
Well, I don't think so... if you see [external-dns](https://github.com/kubernetes-sigs/external-dns#kubernetes-version-compatibility) matrix. They had to make breaking changes since extensions/v1beta1 is removed from k8s v1.22. 
I'm just worried because there will be k8s API depreciation or even removal in the future that external-secrets uses, so the matrix like [external-dns](https://github.com/kubernetes-sigs/external-dns#kubernetes-version-compatibility) would be better.

**Comment by knelasevero** [comment]
That's true! I guess it doesn't hurt to add a table to be prepared for that. 

Would you be interested in adding that to the docs? Docs that come from users that found a pain point are usually nice since you can add exactly what you wanted to see there :)

We can reopen, and leave it here until this is added to the docs.

**Comment by moolen** [comment]
This was fixed with #992, it's now in the docs.
