### ISSUE TITLE
Separate Conversion Logic for SecretStore Providers

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#912]
All the conversion logic for secretStores conversion are dependent on mapping any Provider change on the same file... which will escalate quickly. When we face breaking changes between providers we should have each provider have their own implementation of ConvertFrom and ConvertTo, and call them appropriately.

**Comment by knelasevero** [comment]
Just as a first step, as discussed in the community meeting:
- Define all options that we have to tackle this
- Start planning for this after GA (1.0)
- Keep an eye out and make sure our changes until then are still allowing us to go in this direction

**Comment by serdarkalayci** [comment]
Hey there,
We were discussing over this issue with @gusfcarvalho and I went to see how KEDA handles this as they also have community Scalers (like our SecretStore definitions). I'll try to summarize my findings here.
First and foremost, KEDA does not have anything specific for their scaler targets in their CRDs. Anything specific to their triggers go into a` map[string]string `field called `metadata`
```
// ScaleTriggers reference the scaler that will be used
type ScaleTriggers struct {
	Type string `json:"type"`
	// +optional
	Name     string            `json:"name,omitempty"`
	Metadata map[string]string `json:"metadata"`
	// +optional
	AuthenticationRef *ScaledObjectAuthRef `json:"authenticationRef,omitempty"`
	// +optional
	MetricType autoscalingv2beta2.MetricTargetType `json:"metricType,omitempty"`
}
```
[scaledobject_types.go](https://github.com/kedacore/keda/apis/keda/v1alpha1/scaledobject_types.go)
Inside `pkg/scalers` folder, each scaler has to define its metadata struct and has the responsibility to parse from metadata field into that struct. If there's an unexpected input (like a non-optional field missing) the parse function returns error and operator logs it. This way, even if there is a breaking change for a scaler, they just log it and continue to work, expecting the user to fix their manifest. Also they never have to update their CRDs due to a change from a scaler.
Also I talked to two of their maintainers, and they told me that they are not allowing breaking changes from community scalers for minor versions. In terms of major versions, because their CRDs not forcing the user to update theirs after the update, they believe the changelog will be enough to warn the users before the upgrade as a major version is a long process.
Being said that, I like the idea of not changing CRDs due to provider changes as I discussed this with @gusfcarvalho earlier. Trusting the user to update their manifests based on changelog or the operator log itself might seem a bit intimidating but I still think it's better than forcing a CRD update.
